spring.application.name=ZuvocloudAutomotive
spring.datasource.url=jdbc:mysql://localhost:3306/zuvo_automotive
spring.datasource.username = root
spring.datasource.password = Devendra@123
spring.jpa.hibernate.dd1-auto=update
spring.jpa.show-sql= true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.tool.hbm2ddl=debug

server.port=9091